name: Ejecutar Agente Investigador

on:
  workflow_dispatch:

jobs:
  investigar:
    runs-on: ubuntu-latest
    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }} # Aquí le pasamos la llave
    
    steps:
      - name: Descargar mi codigo
        uses: actions/checkout@v4
        
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Instalar herramientas (requests)
        run: pip install requests
        
      - name: Despertar al Agente Investigador
        run: python investigador.py

